### ISSUE TITLE
This plugin breaks XHTML compatibility 

### ISSUE THREAD

**Issue by heinrichheine** [heinrichheine/dokuwiki-imagereference#4]
This plugin breaks XHTML compatibility because it adds a <div> tag inside a <p> tag. To fix it, change line 61 from

```
function getPType(){ return 'normal';}
```

to

```
function getPType(){ return 'block';}
```

**Comment by heinrichheine** [comment]
fixed by splitting the syntax plugin into two classes. The tags are now xhtml compatible

**Comment by Klap-in** [comment]
I propose an alternative implementation, by using spans. See also 2c3fd5df8a (sorry for the big commit).
